services:
  postgres:
    image: postgres:latest
    container_name: safahat-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: safahat_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: safahat-api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=safahat_db;Username=postgres;Password=password
      - Jwt__Key=FP+yA4+6AS/01NylZL6PXiaXeTHQ1sms9laxbgYMmbg=
      - Jwt__Issuer=safahat-api
      - Jwt__Audience=safahat-client
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs

volumes:
  postgres-data: